name: Deploy Pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  prod:
    name: Deploy to Prod
    uses: ./.github/workflows/deploy-to-aws.yaml
    with:
      environment: prod
    secrets: inherit
