name: Deploy Pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  pre-deploy:
    name: Pre-Flight
    uses: ./.github/workflows/pre-deploy.yaml
  dev:
    name: Deploy
    uses: ./.github/workflows/dev-deploy.yaml
    secrets: inherit
    needs: pre-deploy
  prod:
    name: Deploy
    uses: ./.github/workflows/prod-deploy.yaml
    secrets: inherit
    needs: dev
