name: Deploy
on:
  push:
jobs:
  code-quality:
    uses: ./.github/workflows/code_quality.yaml
    with:
      python-version: 3.10.11
  dev:
    needs: code-quality
    uses: ./.github/workflows/dev-deploy.yaml
  prod:
    needs: dev
    uses: ./.github/workflows/prod-deploy.yaml
