name: Deploy
on:
  push:
jobs:
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/code_quality.yaml
    with:
      python-version: 3.10.11
  dev:
    name: Deploy to Dev
    needs: code-quality
    uses: ./.github/workflows/dev-deploy.yaml
  prod:
    name: Deploy to Prod
    needs: dev
    uses: ./.github/workflows/prod-deploy.yaml
