name: Deploy Pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  code-quality:
    if: github.event.pull_request.merged == true
    name: Code Quality
    uses: ./.github/workflows/code_quality.yaml
    with:
      python-version: 3.10.11
  pre-deploy:
    name: Pre-Flight
    needs: code-quality
    uses: ./.github/workflows/pre-deploy.yaml
  dev:
    name: Deploy
    needs: pre-deploy
    uses: ./.github/workflows/dev-deploy.yaml
  prod:
    name: Deploy
    needs: dev
    uses: ./.github/workflows/prod-deploy.yaml
