name: Deploy Pipeline
on:
  push:
jobs:
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/code_quality.yaml
    with:
      python-version: 3.10.11
  pre-deploy:
    name: Pre-Flight
    needs: code-quality
    uses: ./.github/workflows/pre-deploy.yaml
  dev:
    name: Deploy
    needs: pre-deploy
    uses: ./.github/workflows/dev-deploy.yaml
  prod:
    name: Deploy
    needs: [code-quality, pre-deploy, dev]
    uses: ./.github/workflows/prod-deploy.yaml
