name: Deploy
on:
  push:
jobs:
  code-quality:
    uses: ./.github/workflows/code_quality.yaml
    with:
      python-version: 3.10.11
  pre-deploy:
    name: Pre-Deploy
    needs: code-quality
    uses: ./.github/workflows/pre-deploy.yaml
  dev:
    needs: pre-deploy
    uses: ./.github/workflows/dev-deploy.yaml
  prod:
    needs: [code-quality, pre-deploy, dev]
    uses: ./.github/workflows/prod-deploy.yaml
