name: Deploy
on:
  push:
jobs:
  code-quality:
    uses: ./.github/workflows/code_quality.yaml
    with:
      python-version: 3.10.11
  dev:
    runs-on: ubuntu-latest
    needs: code-quality
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
      - name: Deploy CDK to AWS
        run: |
          echo "Deploying CDK to AWS ${{ vars.STAGE }}"
  qa:
    runs-on: ubuntu-latest
    needs: dev
    environment: qa
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
      - name: Deploy CDK to AWS
        run: |
          echo "Deploying CDK to AWS ${{ vars.STAGE }}"
  prod:
    runs-on: ubuntu-latest
    needs: qa
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
      - name: Deploy CDK to AWS
        run: |
          echo "Deploying CDK to AWS ${{ vars.STAGE }}"
