name: Deploy to DEV
on:
  workflow_call:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::334037273999:role/github.to.aws.oidc
          role-duration-seconds: 3600
      - name: Install Dependencies
        run: |
          npm install -g aws-cdk aws-cli
      - name: Test AWS connection
        run: |
          aws sts get-caller-identity
      - name: Deploy CDK to AWS
        run: |
          echo "Deploying CDK to AWS ${{ vars.STAGE }}"
