on:
  workflow_call:
jobs:
  deploy:
    name: Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Deploy CDK to AWS
        run: |
          echo "Deploying CDK to AWS ${{ vars.STAGE }}"
