name: Pre Deployment Checks
on:
  workflow_call:
jobs:
  list:
    name: CDK List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - name: Install dependencies
        run: |
          npm i
      - name: Listing Stacks to be Deployed
        run: |
          cdk list
  synth:
    name: CDK Synth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - name: Install dependencies
        run: |
          npm i
      - name: Synthesize CDK
        run: |
          cdk synth
