name: Deploy to Prod
on:
  workflow_call:
jobs:
  deploy:
    name: Prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Deploy CDK to AWS
        run: |
          echo "Deploying CDK to AWS ${{ vars.STAGE }}"
