on:
  push:
    branches:
      - main
jobs:
  # call lint job
  lint:
    uses: ./.github/workflows/lint.yaml@main
    with:
      python-version: 3.10
  # call test job
  test:
    uses: ./.github/workflows/coverage.yaml@main
    with:
      python-version: 3.10
